### ISSUE TITLE
Allow optional comparison block to be provided to insertOrUpdate(intermediates) function

### ISSUE THREAD

**Issue by BendyWalker** [3Squared/PeakCoreData#12]
UUIDs generated locally are uppercase strings but are sent back down from our web service as lowercase strings. This causes an issue when inserting/updating since the two strings are incomparable.

Changing subsequent fields/attributes in our data model and `Codable` representations to the `UUID` class would solve this problem, but this is only supported in iOS 11 and above.

A workaround would be to add an optional comparison block parameter to the `insertOrUpdate(intermediates)` function.

**Comment by zilmarinen** [comment]
This is no longer an issue after updating `UniqueIdentifiable` to use an associated type for the `uniqueIDValue` `UniqueIDType` 👍
